version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    image: gramo37/chess-backend:latest
    ports: 
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: "SECRET_KEY"
      NODE_ENV: "production"
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      REDIS_KEY: "REDIS_KEY"
      REDIS_DATA_KEY: "data"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
    volumes:
      - backend_logs:/app/logs

  ws:
    image: gramo37/chess-ws:latest
    ports: 
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: "SECRET_KEY"
      NODE_ENV: "production"
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      REDIS_KEY: "REDIS_KEY"
      REDIS_DATA_KEY: "data"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
    volumes:
      - ws_logs:/app/logs

  frontend:
    image: gramo37/chess-frontend:latest
    args:
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ws
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: "SECRET_KEY"
      NODE_ENV: "production"
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      REDIS_KEY: "REDIS_KEY"
      REDIS_DATA_KEY: "data"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - frontend_static:/usr/share/nginx/html

volumes:
  postgres_data:
  redis_data:
  backend_logs:
  ws_logs:
  frontend_static:
